ALTER TABLE meetings ADD COLUMN cancelled BOOLEAN DEFAULT FALSE;
ALTER TABLE meetings ADD COLUMN cancelled_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE meetings ADD COLUMN cancel_reason TEXT;
ALTER TABLE meetings ADD COLUMN ended_at TIMESTAMP WITH TIME ZONE;
